apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090  # Replace with the correct URL of your Prometheus instance
    isDefault: true
    editable: true
