services:
  postgres:
    container_name: transcendence_postgres
    image: postgres
    build:
      context: services/postgres
    env_file: .env
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - transcendence_network
    restart: always
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  database_data:
    name: database_data
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/database_data
      o: bind

networks:
  transcendence_network:
    name: transcendence_network
    driver: bridge