# Generated by Django 5.1.4 on 2025-01-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_pong_draws_user_pong_losses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='game_stats_id',
        ),
        migrations.AddField(
            model_name='ponggamestats',
            name='number_of_bounces',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ponggamestats',
            name='score_opponent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ponggamestats',
            name='score_player',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tictactoegamestats',
            name='board_state',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='tictactoegamestats',
            name='total_moves',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tictactoegamestats',
            name='winning_move_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
