# Generated by Django 5.1.4 on 2025-01-29 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_match_game_stats_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='pong_game_stats',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match', to='api.ponggamestats'),
        ),
        migrations.AddField(
            model_name='match',
            name='tictactoe_game_stats',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match', to='api.tictactoegamestats'),
        ),
    ]
