# Generated by Django 4.2.17 on 2024-12-12 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PongGameStats',
            fields=[
                ('pong_game_stats_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TicTacToeGameStats',
            fields=[
                ('tictactoe_game_stats_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('tournament_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password_hash', models.CharField(max_length=255)),
                ('password_salt', models.CharField(max_length=255)),
                ('avatar_url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language_code', models.CharField(max_length=2)),
                ('auth_token', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentParticipant',
            fields=[
                ('tournament_participant_id', models.AutoField(primary_key=True, serialize=False)),
                ('points', models.FloatField()),
                ('rank', models.IntegerField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('result', models.CharField(max_length=4)),
                ('is_pong', models.BooleanField()),
                ('game_stats_id', models.IntegerField()),
                ('tournament_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opponent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent_user', to='main_app.user')),
                ('player_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_user', to='main_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('friendship_id', models.AutoField(primary_key=True, serialize=False)),
                ('friendship_status', models.BigIntegerField()),
                ('user_id_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_user_1', to='main_app.user')),
                ('user_id_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_user_2', to='main_app.user')),
            ],
        ),
    ]
